version: '3'
services: 
  banco:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: cami
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: devops
  api:
    build: 
      context: ./api
    environment:
      DB: "postgres://cami:devops123@banco:5432/devops"
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    environment:
      API_HOST: http://api:3000