version: "3.9"

networks:
  frontend:
  backend:

services:
  db:
    image: postgres:alpine
    hostname: postgres-db
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - backend

  api:
    hostname: web_api
    container_name: web_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    hostname: ipi-devops
    container_name: api-devops
    environment:
      PORT: 8081
      DB: "postgres://test:test@localhost:5432/test"
      DB_HOST: db
      DB_USER: test
      DB_DATABASE: test
      DB_PASSWORD: test
      DB_PORT: 5432
    ports:
      - 8081:8081
    networks:
      - backend
      - frontend
  web:
    hostname: web_frontend
    container_name: web_frontend
    build:
      context: ./web
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
      API_HOST: http://api:8081
    build: ./web
    ports:
      - 8080:8080
    networks:
      - frontend
